### ISSUE TITLE
Any help or suggestions for how to get into this?

### ISSUE THREAD

**Issue by Parinz** [aptigges21/gentoo-sp6#1]
Hey, fellow surface owner here. I have a Surface Laptop 2, I'm not quite familiar with Gentoo but I am quite familiar with Linux in general. I personally run Arch Linux with the Surface-Linux kernel. 

I know a bit about applying patches, however could you please guide me through the process of installing Gentoo and applying the patches?

The problem is that right now I can't seem to get wpa_supplicant to work on the bootable installation.

Many thanks!

**Comment by aptigges21** [comment]
Apologies for the late response -- hopefully my advice is still relevant as I also remember having problems with wpa_supplicant when I was getting started. Also, I am assuming you compiled your own kernel and did not use genkernel.

Wireless should work without the kernel patches so lets get you connected to the internet before adding the patches. First, make sure that you have the correct kernel options for Marvell Wifi devices. To check, I would do the following:

1.  `make nconfig` in your `/usr/src/linux`
2. Go to `Device Drivers > Network Device Support > Wireless LAN`
3. Select Yes on Marvell Devices - [*]
4. Select Marvell WiFi-Ex Driver as a module and the PCIE submenu also as a module - <M>
5. Recompile and install the kernel

Next thing to check is that you have the correct firmware for wireless. I installed Arch Linux once and remember installing a firmware package by following the instructions. In Gentoo this is labeled as optional at the bottom of the kernel page. However, in your case, it is required for using wifi. Simply performing `emerge -aq sys-kernel/linux-firmware` will solve this. You can check the firmware is there by checking you have a populated `/lib/firmware/mrvl` folder. Later on, I recommend reading [https://wiki.gentoo.org/wiki/Linux_firmware](url) to learn about using the "savedconfig" use flag so you do not have unnecessary firmware installed. 

For getting wpa_supplicant to work there is no surface specific configuration. Just make sure you are following the wiki article closely [https://wiki.gentoo.org/wiki/Wpa_supplicant](url). One thing you can also try is declaring your interface using the `-i` option. This did not prevent me from starting wpa_supplicant manually, but it would often fail on startup. My `/etc/conf.d/wpa_supplicant` looks like `wpa_supplicant_args='-B -M -i wlp1s0 -c/etc/wpa_supplicant/wpa_supplicant.conf`

Hopefully one of these things solved the problem for you but if not feel free to let me know!
Drew

**Comment by Parinz** [comment]
Sorry I’m really new to Gentoo. So since the Wi-Fi isn’t working on the Bootable USB I could install gentoo off of another distro’s usb (such as arch). Then... when I compile the kernel, I do the steps you described and wpa_supplicant will work from the newly installed gentoo?

**Comment by aptigges21** [comment]
Ah I miss interpreted what you were saying... I thought by "bootable installation" you meant that you had installed gentoo and could boot but had problems with wpa_supplicant afterward. My first reply will not be helpful to you yet (although it may be in the future). 

I must say that this is not a problem that I have encountered before. Since I do not believe that this has to do with you having a surface device, I might also advise you to seek help on the gentoo forum if the issue persists. 

To check I remade a live usb from [https://www.gentoo.org/downloads/](url) and booted into it. My steps for connecting to my wifi network are as follows:

1.  Type `net-setup`
2.  Press enter on `wlp1s0` (or variant although I assume its the same)
3.  Press enter on yes
4.  Press enter on the bottom selection that says `My network is wireless (WPA-PSK/WPA2-PSK)`
5.  Type in your SSID (name of the network you would like to connect to)
6.  Enter the password for the network

Your needs for your particular network may differ slightly from this but I feel this will work in the majority of cases.

If `ping -c 3 www.gentoo.org` fails after this I would try to run `lspci -k` to make sure that the proper wifi driver and module are loaded. For me this is `mwifiex_pcie`. If it is not you could try `modproble mwifiex_pcie` and retrying the `net-setup`.

Drew

**Comment by Parinz** [comment]
Update: I managed to get Gentoo installed through using Ubuntu Live CD. The problem now, is that Gentoo doesn’t show the wireless interface . What I’ve done during install:

1. Emerged Linux-Firmware
2. Built kernel with Marvell support *built-in*
3. /lib/firmware/mrvl is populated

I’ve checked the dmesg it says that
`Direct Firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
`
![image](https://user-images.githubusercontent.com/30139280/104831941-d9bd6d00-58bf-11eb-8f25-700f9abe413f.jpg)

**Comment by Parinz** [comment]
My apologizes that whole jumble was my fault. I missed the detail about compiling the drivers as **Modules** not **Built-in**. Alright! I’ve got WiFi up and running thanks to you! Thank you very much!

Now... for the kernel part. Thanks in advance

**Comment by aptigges21** [comment]
I hope I don't have any typos but I think most of these steps should be self-explanatory:

1. `sudo -s` or `su`
2. `echo sys-kernel/gentoo-sources ~amd64 >> /etc/portage/package.accept_keywords`
3. `emerge -aq gentoo-sources` -- Note is should have an "N" or "NS" instead of a "R"
4. `cd /usr/src`
5. Ensure you have installed git with `emerge -aqn dev-vcs/git` -- if it does nothing you have already installed it
6. `git clone https://github.com/linux-surface/linux-surface`
7. `git clone https://github.com/aptigges21/gentoo-sp6`
8. `rm linux && ln -s /usr/src/linux-5.10.7-gentoo linux`
9. `cp gentoo-sp6/config linux/.config`
10. `cd linux`
11. `for i in ../linux-surface/patches/5.10/*.patch; do patch -p1 < $i; done`
12. `make nconfig` -- push "8" to search and type "SURFACE" to make sure most of the entries that come are selected as a module
13. `make -j8 && make -j8 modules_install && make install`
14. `grub-mkconfig -o /boot/grub/grub.cfg`
15. Then you just have to reboot. Once you are in you can do `uname -r` to confirm you are running the correct kernel

**Comment by aptigges21** [comment]
To elaborate on what was performed to get the newer kernel:
All of the configuration you will do for portage will be done in the `/etc/portage` folder. There are a few main folders and files that you will need to use to fully customize your Gentoo build. 
**Note**: almost everything in `/etc/portage` can either be a simple file or a folder. If you choose to use a folder, the files within the folder will be read alphabetically.

`/etc/portage/package.use/*` -- All of the files in this folder control your "USE" flags for specific programs. For example, I use the xwallpaper program to set a wallpaper for my window manager. However, this package does not include jpeg or png support by default. Thus I have a file called `xwalllpaper` in `/etc/portage/package.use` (the names do not matter, just remember they are read alphabetically) that has `x11-misc/xwallpaper jpeg png` in it. Then I can recompile the program simply by doing `emerge -aq xwallpaper`. To see the use flags before compiling I always do `emerge -pv [name of package]`. To learn what all the options for emerge are read `man emerge`.

`/etc/portage/package.accept_keywords` -- This file allows you to emerge packages that are "testing". The fact that they are testing isn't necessarily a bad thing and I run many packages on my machines that are considered "testing". For example, look at [https://packages.gentoo.org/packages/sys-kernel/gentoo-sources](url). You will see many ebuilds in yellow that are the packages considered "testing" and some in green that are considered "stable". Portage will always default for the "stable" ebuilds and that is why you received kernel 5.4.80.  To accept all keywords for a package you cant use `**`. For example I use Neovim 5.0 that requires me to build the nightly version. Gentoo makes this very simple. All I had to do was add `app-editors/neovim **` to my `package.accept_keywords` and re-emerge.

There are explanations of the others on the gentoo wiki. For practice you could try emerging spotify to see if you can figure out the keywords to accept and the licenses to accept. Once you figured it out you could just cancel the emerge  and delete the edits you did if you don't want spotify. Another one to do is to add the intel microcode explained in [https://wiki.gentoo.org/wiki/Intel_microcode](url).

**Comment by Parinz** [comment]
Thank you very much, I'll keep you updated with my progress!

**Comment by Parinz** [comment]
Can't thank you enough, the patches are working and everything is now good! Thank you very very much! I think we close this now.

**Comment by aptigges21** [comment]
Awesome! Feel free to open another issue if more problems arise.
